"""Backtesting domain records and lifecycle validation."""

from .acceptance import (
    AcceptanceCheck,
    AcceptanceStatus,
    PerformanceScope,
    PerformanceSlice,
    HorizonAcceptanceEvidence,
    IndependentHorizonAcceptanceReport,
    StrategyAcceptanceReport,
    StrategyAcceptanceThresholds,
    build_strategy_acceptance_report,
    build_independent_horizon_acceptance_report,
)

from .economics import (
    BindingConstraint,
    ExecutionCostModel,
    PositionSizeDecision,
    PositionSizingConstraints,
    PositionSizingError,
    TradeSettlement,
    apply_entry_slippage,
    apply_exit_slippage,
    apply_position_size,
    calculate_fee,
    calculate_position_size,
    settle_trade,
    validate_order_quantity,
)

from .execution import (
    ExecutionResult,
    ExecutionStatus,
    FillRule,
    execute_next_session,
)

from .model import (
    BacktestLifecycle,
    ClosedTradeRecord,
    ExitReason,
    FillRecord,
    LifecycleEvent,
    LifecycleEventType,
    OrderRecord,
    PositionRecord,
    PositionSide,
    SignalRecord,
    side_from_signal,
)

from .performance import (
    BuyAndHoldComparison,
    EquityPoint,
    PerformanceReport,
    SettledTrade,
    calculate_max_drawdown,
    calculate_performance,
    calculate_sharpe_ratio,
)

from .release import (
    APPROVED_THRESHOLD_STATUS,
    DEFAULT_P2_LIMITATIONS,
    REQUIRED_REGRESSION_PHASES,
    ApprovedThresholdManifest,
    P2ReleaseGateReport,
    RegressionEvidence,
    ReleaseGateStatus,
    evaluate_p2_release_gate,
    load_approved_threshold_manifest,
)

from .validation import (
    CandidateEvaluation,
    ChronologicalSplit,
    FoldValidationResult,
    ParameterStabilityEntry,
    ParameterStabilityReport,
    PromotionDecision,
    PromotionThresholds,
    WalkForwardConfig,
    WalkForwardFold,
    WalkForwardValidationReport,
    WindowMode,
    assess_strategy_promotion,
    calculate_parameter_stability,
    chronological_train_test_split,
    create_walk_forward_folds,
    run_walk_forward_validation,
)

__all__ = [
    "APPROVED_THRESHOLD_STATUS",
    "DEFAULT_P2_LIMITATIONS",
    "REQUIRED_REGRESSION_PHASES",
    "ApprovedThresholdManifest",
    "P2ReleaseGateReport",
    "RegressionEvidence",
    "ReleaseGateStatus",
    "evaluate_p2_release_gate",
    "load_approved_threshold_manifest",
    "AcceptanceCheck",
    "AcceptanceStatus",
    "PerformanceScope",
    "PerformanceSlice",
    "HorizonAcceptanceEvidence",
    "IndependentHorizonAcceptanceReport",
    "StrategyAcceptanceReport",
    "StrategyAcceptanceThresholds",
    "build_strategy_acceptance_report",
    "build_independent_horizon_acceptance_report",
    "CandidateEvaluation",
    "ChronologicalSplit",
    "FoldValidationResult",
    "ParameterStabilityEntry",
    "ParameterStabilityReport",
    "PromotionDecision",
    "PromotionThresholds",
    "WalkForwardConfig",
    "WalkForwardFold",
    "WalkForwardValidationReport",
    "WindowMode",
    "assess_strategy_promotion",
    "calculate_parameter_stability",
    "chronological_train_test_split",
    "create_walk_forward_folds",
    "run_walk_forward_validation",
    "BuyAndHoldComparison",
    "EquityPoint",
    "PerformanceReport",
    "SettledTrade",
    "calculate_max_drawdown",
    "calculate_performance",
    "calculate_sharpe_ratio",
    "BindingConstraint",
    "ExecutionCostModel",
    "PositionSizeDecision",
    "PositionSizingConstraints",
    "PositionSizingError",
    "TradeSettlement",
    "apply_entry_slippage",
    "apply_exit_slippage",
    "apply_position_size",
    "calculate_fee",
    "calculate_position_size",
    "settle_trade",
    "validate_order_quantity",
    "ExecutionResult",
    "ExecutionStatus",
    "FillRule",
    "execute_next_session",
    "BacktestLifecycle",
    "ClosedTradeRecord",
    "ExitReason",
    "FillRecord",
    "LifecycleEvent",
    "LifecycleEventType",
    "OrderRecord",
    "PositionRecord",
    "PositionSide",
    "SignalRecord",
    "side_from_signal",
]
