"""Persistent automated paper-portfolio package."""

from .database import (
    DEFAULT_DATABASE_PATH,
    connect_database,
    transaction,
)
from .event_risk import (
    EVENT_RISK_POLICY_VERSION,
    EventEvidenceStatus,
    EventRiskAction,
    EventRiskContext,
    EventRiskDecision,
    SecurityEvent,
    SecurityEventType,
    evaluate_event_risk,
)
from .exit_policy import (
    ManagedExitDecision,
    evaluate_managed_long_exit,
)
from .fx import (
    FXRateError,
    FXRateProvider,
    QuoteToPortfolioFXRate,
    StaticFXRateProvider,
    identity_fx_rate,
)
from .yahoo_fx import (
    YahooFXRateProvider,
)
from .ledger import (
    LongTradeCalculation,
    calculate_entry_cash,
    calculate_long_trade,
)
from .migrations import (
    SCHEMA_VERSION,
    apply_migrations,
    initialize_database,
)
from .models import (
    AccountReconciliation,
    AccountStatus,
    BenchmarkObservation,
    ClosedPaperTrade,
    IncidentSeverity,
    IncidentStatus,
    NotificationChannel,
    NotificationRecord,
    NotificationStatus,
    OperationalIncident,
    OrderStatus,
    PaperAccount,
    PaperExitReason,
    PaperFillRecord,
    PaperOrderRecord,
    PaperPositionRecord,
    PositionValuationObservation,
    PersistedSignal,
    PositionStatus,
    SystemEventRecord,
    money,
)
from .proposal import (
    CostAwareOrderProposal,
    CostAwareOrderProposalRequest,
    OrderProposalRejected,
    propose_cost_aware_us_long_order,
)
from .repository import PaperRepository
from .service import (
    PaperPortfolioConfig,
    PaperTradingService,
)
from .sizing import (
    FixedNotionalSizingDecision,
    FixedNotionalSizingPolicy,
    FixedNotionalSizingRequest,
    PositionSizingConstraint,
    PositionSizingMode,
    PositionSizingRejected,
    calculate_fixed_notional_size,
    fixed_notional_policy_from_product_policy,
)

__all__ = [
    "DEFAULT_DATABASE_PATH",
    "EVENT_RISK_POLICY_VERSION",
    "SCHEMA_VERSION",
    "AccountReconciliation",
    "AccountStatus",
    "BenchmarkObservation",
    "ClosedPaperTrade",
    "IncidentSeverity",
    "IncidentStatus",
    "CostAwareOrderProposal",
    "CostAwareOrderProposalRequest",
    "FixedNotionalSizingDecision",
    "FixedNotionalSizingPolicy",
    "FixedNotionalSizingRequest",
    "EventEvidenceStatus",
    "EventRiskAction",
    "EventRiskContext",
    "EventRiskDecision",
    "FXRateError",
    "FXRateProvider",
    "LongTradeCalculation",
    "ManagedExitDecision",
    "NotificationChannel",
    "NotificationRecord",
    "NotificationStatus",
    "OperationalIncident",
    "OrderProposalRejected",
    "OrderStatus",
    "PaperAccount",
    "PaperExitReason",
    "PaperFillRecord",
    "PaperOrderRecord",
    "PaperPortfolioConfig",
    "PaperPositionRecord",
    "PositionValuationObservation",
    "PaperRepository",
    "PaperTradingService",
    "PersistedSignal",
    "QuoteToPortfolioFXRate",
    "PositionSizingConstraint",
    "PositionSizingMode",
    "PositionSizingRejected",
    "PositionStatus",
    "SecurityEvent",
    "SecurityEventType",
    "StaticFXRateProvider",
    "SystemEventRecord",
    "YahooFXRateProvider",
    "apply_migrations",
    "calculate_entry_cash",
    "calculate_fixed_notional_size",
    "calculate_long_trade",
    "connect_database",
    "evaluate_event_risk",
    "evaluate_managed_long_exit",
    "fixed_notional_policy_from_product_policy",
    "identity_fx_rate",
    "initialize_database",
    "money",
    "propose_cost_aware_us_long_order",
    "transaction",
]
